name: Tests

on: [push, pull_request]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18']
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Setup pokeapi/api-data
        run: |
          pnpm run apidata:clone
          pnpm run apidata:replace
      - name: Build
        run: |
          pnpm run generate:types
          pnpm run generate:main
          pnpm run generate:jsdocs
      - name: Unit test
        run: |
          pnpm t
  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Setup pokeapi/api-data
        run: |
          npm run apidata:clone
          npm run apidata:replace
      - name: Build
        run: |
          npm run generate:types
          npm run generate:main
          npm run generate:jsdocs
      - name: Unit test
        run: |
          npm t

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: |
          npm run lint
