name: Tests

on: [push, pull_request]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Setup pokeapi/api-data
        run: |
          pnpm run apidata:clone
          pnpm run apidata:replace
      - name: Build
        run: |
          pnpm run generate:types
          pnpm run generate:main
          pnpm run generate:jsdocs
      - name: Unit test
        run: |
          pnpm t
  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20', 'lts/*']
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Setup pokeapi/api-data
        run: |
          npm run apidata:clone
          npm run apidata:replace
      - name: Build
        run: |
          npm run generate:types
          npm run generate:main
          npm run generate:jsdocs
      - name: Unit test
        run: |
          npm t

  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Setup pokeapi/api-data
        run: |
          bun run apidata:clone
          bun run apidata:replace
      - name: Build
        run: |
          bun run generate:types
          bun run generate:main
          bun run generate:jsdocs
      - name: Unit test
        run: |
          bun run test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: |
          npm run lint
